desiredUser:
    #name: "ğŸŸ‡ ğ™ğ™ªğ™¥ğ™šğ™§ Cosmic"
    name: "ğŸŸ‡ Cosmic âš *help"
    color: "#1d0054"
agents:
    #wss://smnmpp.hri7566.info:8443:
    #    - id: "lobby"
    wss://mppclone.com:
        #- id: "âœ§ğ““ğ“”ğ“¥ ğ“¡ğ“¸ğ“¸ğ“¶âœ§"
        #- id: "Hree7566"
        - id: "{midi-test}"
